# conda env update --file environment.yml --prune
# conda env create --file environment.yml 
name: 'fundaml'
channels:
  - conda-forge
  - pytorch
  - anaconda
  - defaults
dependencies:
  - ipykernel
  - python=3.10
  - jupyter 
  - cookiecutter
  - numpy
  - ipykernel
  - python-semantic-release
  - pytorch
  - torchvision
  - torchaudio
  - matplotlib
  - pip>=20
  - pip:
    - cookiecutter
    - docopt-ng
    - poetry
    - torch-summary
    - torchviz  
    - tensorboard
    - tokenizers 
    - transformers  
