# conda env update --file environment.yml --prune
# conda env create --file environment.yml 
name: 'mltz_base'
channels:
  - conda-forge
  - districtdatalabs
  - pytorch
  - defaults
dependencies:
  - python>=3.11
  - cookiecutter
  - numpy
  - ipykernel
  - python-semantic-release
  - mypy
  - cpuonly
  - pytorch
  - torchvision
  - torchaudio
  - tensorboard
  - matplotlib
  - pip>=20
  - pip:
    - cookiecutter
    - docopt-ng
    - poetry
